### ISSUE TITLE
Allow Sqlite INTEGER type to be long

### ISSUE THREAD

**Issue by amlcurran** [novoda/sqlite-analyzer#41]
the sqlite INTEGER type can be up to 8-bytes long so can be a short, int, or long, but currently SQLite will only generate a `int` setter - could we add `long` setters too?

**Comment by ouchadam** [comment]
:+1:

**Comment by devisnik** [comment]
The current implementation assumes `int` as the default mapping for the sqlite type `INTEGER` as that should be good enough in most of the use cases. We might re-evaluate that decision based on user feedback. ;)
You can easily define your own mapping though, see https://github.com/novoda/sqlite-analyzer/blob/master/demo-sqliteprovider/build.gradle#L25

**Comment by StylingAndroid** [comment]
+1 from me for this too. SQLite documentation states:

```
INTEGER. The value is a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.
```

Just because it is named `INTEGER` does not mean that there is a direct mapping to Java `Integer` / `int`. The current mapping to `int` is likely to result in data loss as it does not cover the full resolution of values that SQLite can store in an `INTEGER` column.

IMO it would be far safer to map this to a Java `long` than an `int` if no actual dynamic type conversion is in place.

**Comment by amlcurran** [comment]
@devisnik I think we should definitely add longs - for example we are currently storing times as ISO-encoded strings rather than millis since epoch as we'll lose the top bits when trying store values! Perhaps this is a valid enough use case?

**Comment by devisnik** [comment]
@amlcurran @StylingAndroid As pointed out above it should be easy to customise the mapping at the usage side to use `long` if needed. Let me know if you need any help with that.

We'll probably move to `long` in the default mapping soon, thanks for the feedback.
